name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./RV-1.0-rpi_sensors-install
