name: Deploy Production
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: |
            git clone https://github.com/davidweitaiwan/RV-1.0-rpi_sensors.git
            ls
            cp -r ./RV-1.0-rpi_sensors/cpp_webcam/* ./
            ls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: False
          load: true
          tags: gluttony/cpp_webcam:${{ github.run_number }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
      - uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: gluttony/cpp_webcam:${{ github.run_number }}
          path: /app/.
          destination: dist
      - name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          path: dist
