name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: install the Docker 
      run: |
          set +e
          export DOCKER_HOST=unix://${HOME}/.colima/default/docker.sock
          brew install colima
          brew install docker
          colima start
          docker build .


