name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: install the Docker 
      run: |
          set +e
          brew install docker docker-buildx
          docker --version
          echo "FROM ubuntu:latest" > Dockerfile
          docker build --no-cache -t test .

    - name: Build the Docker image
      run: docker build .
